# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ovpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text=b'configuration file', upload_to=b'', verbose_name=b'File (.ovpn)')),
                ('country', models.CharField(max_length=8, verbose_name=b'Country')),
                ('protocol', models.CharField(max_length=8, verbose_name=b'Protocol')),
                ('port', models.IntegerField(verbose_name=b'Port')),
                ('activated', models.BooleanField(default=False, verbose_name=b'Activated')),
            ],
        ),
        migrations.CreateModel(
            name='Vpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name=b'username')),
                ('password', models.CharField(max_length=32, verbose_name=b'password')),
            ],
        ),
        migrations.AddField(
            model_name='ovpn',
            name='vpn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openvpn_control.Vpn', verbose_name=b'VPN'),
        ),
    ]
